In [1]:
# Question 1
import pandas as pd
df = pd.read_csv('Данные для тестового задания - Данные об аудитории.csv')
df.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16814 entries, 0 to 16813
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          16814 non-null  object
 1   user_id       16814 non-null  object
 2   view_adverts  16814 non-null  int64
dtypes: int64(1), object(2)
memory usage: 394.2+ KB

In [3]:
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16814 entries, 0 to 16813
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          16814 non-null  datetime64[ns]
 1   user_id       16814 non-null  object
 2   view_adverts  16814 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 394.2+ KB

In [4]:
mau = df["user_id"].nunique()
print(f"MAU: {mau}")

MAU: 7639

In [6]:
# Question 2
dau = df.groupby("date")["user_id"].nunique()
print(f"DAU: {dau.mean()}")

DAU: 560.4666666666667

In [8]:
# Question 3
first_day = df[df["date"] == "2023-11-01"]["user_id"].unique()
second_day = df[df["date"] == "2023-11-02"]["user_id"].unique()

returned_users = set(first_day) & set(second_day)
retention = len(returned_users) / len(first_day) * 100
print(f"Retention Day 1: {retention}%")

Retention Day 1: 26.64526484751204%

In [9]:
# Question 5
total_users = df["user_id"].nunique()
view_users = df[df["view_adverts"] > 0]["user_id"].nunique()
conversion = view_users / total_users *100
print(f"Conversion: {conversion}%")

Conversion: 46.31496269145176%

In [10]:
# Question 6
user_views = df.groupby("user_id")["view_adverts"].sum()
ave_views = user_views.mean()
print(f"Average views per user: {ave_views}")

Average views per user: 2.8687000916350307

In [12]:
# Question 7
(1200/2000 - 500/2000) * 100

35.0

In [11]:
# Question 8
df2 = pd.read_csv('Данные для тестового задания - Данные АБ тестов.csv')
df2.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2835 entries, 0 to 2834
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   experiment_num    2835 non-null   int64
 1   experiment_group  2835 non-null   object
 2   user_id           2835 non-null   int64
 3   revenue           2835 non-null   int64
dtypes: int64(3), object(1)
memory usage: 88.7+ KB

In [16]:
from scipy.stats import ttest_ind
results = []

for num in df2["experiment_num"].unique():
    data = df2[df2["experiment_num"] == num]
    test = data[data["experiment_group"] == "test"]["revenue"]
    control = data[data["experiment_group"] == "control"]["revenue"]
    t_stat, p_value = ttest_ind(test, control, equal_var = False)
    results.append((num, test.mean(), control.mean(), p_value))
results_df = pd.DataFrame(results, columns = ["experiment", "test_mean", "control_mean", "p_val"])
results_df

   experiment   test_mean  control_mean     p_val
0           1  665.739583    722.460215  0.688966
1           2  332.929167    704.653763  0.001128
2           3  998.668750    663.206452  0.060315

In [17]:
# Question 9
df3 = pd.read_csv('Данные для тестового задания - Листеры.csv')
df3.head()

   user_id        date  cnt_adverts  age  cnt_contacts  revenue
0      100  2022-01-01            6   21           119       53
1      100  2022-01-02            2   21           200       18
2      100  2022-01-03            6   21           193       42
3      100  2022-01-04            2   21           143       38
4      100  2022-01-05            2   21           190       40

In [22]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       158 non-null    int64
 1   date          158 non-null    object
 2   cnt_adverts   158 non-null    int64
 3   age           158 non-null    int64
 4   cnt_contacts  158 non-null    int64
 5   revenue       158 non-null    int64
dtypes: int64(5), object(1)
memory usage: 7.5+ KB

In [19]:
revenue = df3.groupby("user_id")["revenue"].sum()
arpu = revenue.mean()
print(f"Revenue: {arpu}")

Revenue: 156.48387096774192

In [21]:
# Question 10
age = df3.groupby("user_id")["age"].mean()
median_age = age.median()
median_age

28.0

In [24]:
# Question 18
cr_control = 1003 / 100047501
cr_test = 1099 / 100001055
(cr_test - cr_control) * 100

9.646461449836582e-05

In [25]:
from statsmodels.stats.proportion import proportions_ztest
results = [1003, 1099]
users = [100047501, 100001055]

z_stat, p_value = proportions_ztest(results, users)
print(f"z_stat: {z_stat}")
print(f"p-value: {p_value}")

z_stat: -2.1045506019397746
p-value: 0.03533044544854254

In [27]:
from statsmodels.stats.proportion import confint_proportions_2indep

ci_low, ci_high = confint_proportions_2indep(count1 = 1003, nobs1 = 100047501, count2 = 1099, nobs2 = 100001055, method = "wald")
print(f"Confidence interval: {ci_low} - {ci_high}")

Confidence interval: -1.8630288347401895e-06 - -6.626345522712712e-08